version: '3.8'
services:
  chroma:
    image: chromadb/chroma:latest
    environment:
      - ALLOW_RESET=true
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"

volumes:
  chroma_data:
    driver: local
